### ISSUE TITLE
Abrir armario

### ISSUE THREAD

**Issue by henricr109** [PI3-ES-2024-T24/PI3-ES-2024-T24#75]

**Comment by kauanbarbosa** [comment]
15/05 - 14:00 to 16:00 (2 hours)
16/05 - 14:00 to 15:30 (1 hour and 30 minutes)

**Comment by kauanbarbosa** [comment]
21/05 - 14:00 to 17:00 (3 hours)

**Comment by kauanbarbosa** [comment]
22/05 - 13:00 to 16:38 (3 hours and 38 minutes)
